dtl_api_deploy:
    extends:
        file: common.yml
        service: dtl-api
    links:
        - mysql
    environment:
        - NODE_ENV=docker
    command: run start

mysql:
   build: mysql
   ports:
       - "3306:3306"
   volumes_from:
       - mysql-data
   environment:
       - USERNAME=root
       - PASSWORD=verysecret
       - MYSQL_ROOT_PASSWORD=verysecret

mysql-data:
 build: mysql/mysql-data
 volumes:
   - /var/lib/mysql
 command: /bin/true
