api:
    build: ../../
    ports:
        - "3030:3030"
    working_dir: /app
    volumes:
        - ../../:/app
    links:
        - mysql
    environment:
        - NODE_ENV=development
    command: npm run start-dev

mysql:
   build: mysql
   ports:
       - "3306:3306"
   volumes_from:
       - mysql-data
   environment:
       - USERNAME=root
       - PASSWORD=verysecret
       - MYSQL_ROOT_PASSWORD=verysecret

mysql-data:
 build: mysql/mysql-data
 volumes:
   - /var/lib/mysql
 command: /bin/true
